In [1]:
import numpy as np
import tensorflow as tf
import joblib


In [4]:
npz = np.load('../models/Audiobooks_data_train.npz')
train_inputs = npz['inputs'].astype(float)
train_targets = npz['targets'].astype(int)

npz = np.load('../models/Audiobooks_data_validation.npz')
validation_inputs = npz['inputs'].astype(float)
validation_targets = npz['targets'].astype(int)

npz = np.load('../models/Audiobooks_data_test.npz')
test_inputs = npz['inputs'].astype(float)
test_targets = npz['targets'].astype(int)

In [ ]:
### Model definition
input_size = 10
output_size = 2
hidden_layer_size = 50

model = tf.keras.Sequential([
    tf.keras.layers.Dense(hidden_layer_size, activation = 'relu', input_shape = (input_size,)),
    tf.keras.layers.Dense(hidden_layer_size, activation = 'relu'),
    tf.keras.layers.Dense(output_size, activation = 'softmax')
])

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

batch_size = 100
max_epochs = 100
early_stopping = tf.keras.callbacks.EarlyStopping(patience = 2)

model.fit(train_inputs, train_targets,
          batch_size = batch_size,
          epochs = max_epochs,
          validation_data = (validation_inputs, validation_targets),
          callbacks = [early_stopping],
          verbose = 2)
test_loss, test_accuracy = model.evaluate(test_inputs, test_targets)
print('Test loss: {0:.2f}. Test accuracy: {1:.2f}.'.format(test_loss, test_accuracy))

Epoch 1/100


/Users/senayberhe/Desktop/customer_segmentation/.venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


36/36 - 1s - 20ms/step - accuracy: 0.7756 - loss: 0.5481 - val_accuracy: 0.8635 - val_loss: 0.4211
Epoch 2/100
36/36 - 0s - 2ms/step - accuracy: 0.8718 - loss: 0.3758 - val_accuracy: 0.8859 - val_loss: 0.3248
Epoch 3/100
36/36 - 0s - 2ms/step - accuracy: 0.8807 - loss: 0.3282 - val_accuracy: 0.8904 - val_loss: 0.2995
Epoch 4/100
36/36 - 0s - 2ms/step - accuracy: 0.8852 - loss: 0.3076 - val_accuracy: 0.8971 - val_loss: 0.2818
Epoch 5/100
36/36 - 0s - 2ms/step - accuracy: 0.8888 - loss: 0.2941 - val_accuracy: 0.8993 - val_loss: 0.2684
Epoch 6/100
36/36 - 0s - 2ms/step - accuracy: 0.8916 - loss: 0.2853 - val_accuracy: 0.9060 - val_loss: 0.2565
Epoch 7/100
36/36 - 0s - 2ms/step - accuracy: 0.8947 - loss: 0.2773 - val_accuracy: 0.9038 - val_loss: 0.2508
Epoch 8/100
36/36 - 0s - 1ms/step - accuracy: 0.8980 - loss: 0.2698 - val_accuracy: 0.9128 - val_loss: 0.2475
Epoch 9/100
36/36 - 0s - 2ms/step - accuracy: 0.8997 - loss: 0.2665 - val_accuracy: 0.9128 - val_loss: 0.2440
Epoch 10/100
36/36 - 

#### Obtain the probability for a customer to convert ####

In [7]:
model.predict(test_inputs[:10]).round(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


array([[0.1 , 0.9 ],
       [1.  , 0.  ],
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.81, 0.19],
       [1.  , 0.  ],
       [0.28, 0.72],
       [0.22, 0.78],
       [0.05, 0.95],
       [0.81, 0.19]], dtype=float32)

In [9]:
model.predict(test_inputs)[:,1].round(0)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step


array([1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 0., 1., 0.

In [10]:
np.argmax(model.predict(test_inputs), axis=1)

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step


array([1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,

In [ ]:
### Save the model
model.save('../models/deep_learning_model.keras')