In [1]:
import numpy as np
import joblib
import tensorflow as tf

In [3]:
scaler_deep_learning = joblib.load('../models/scaler_deep_learning.bin')
model = tf.keras.models.load_model('../models/deep_learning_model.keras')

/Users/senayberhe/Desktop/customer_segmentation/.venv/lib/python3.10/site-packages/keras/src/saving/saving_lib.py:794: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [8]:
raw_data = np.loadtxt('../data/New_Audiobooks_Data.csv', delimiter=',' )

In [9]:
new_data_inputs = raw_data[:, 1:]

In [10]:
new_data_inputs_scaled = scaler_deep_learning.transform(new_data_inputs)

In [11]:
model.predict(new_data_inputs_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[9.8628891e-01, 1.3711148e-02],
       [9.9999917e-01, 8.7227528e-07],
       [9.3080175e-01, 6.9198228e-02],
       [1.4660731e-05, 9.9998534e-01],
       [9.9579018e-01, 4.2098835e-03],
       [9.4397950e-01, 5.6020427e-02],
       [9.4916993e-01, 5.0830096e-02],
       [8.6679399e-01, 1.3320594e-01],
       [9.4923776e-01, 5.0762177e-02],
       [1.9910920e-01, 8.0089080e-01],
       [9.9994957e-01, 5.0366813e-05],
       [1.8442896e-01, 8.1557107e-01],
       [5.5801932e-02, 9.4419807e-01],
       [9.9991125e-01, 8.8756511e-05],
       [8.8392156e-01, 1.1607849e-01],
       [8.8032669e-01, 1.1967325e-01],
       [1.3456610e-01, 8.6543393e-01],
       [2.3702547e-01, 7.6297462e-01],
       [1.3931493e-01, 8.6068505e-01],
       [2.5351651e-02, 9.7464830e-01],
       [2.0114912e-04, 9.9979883e-01],
       [1.2874525e-03, 9.9871254e-01],
       [4.0262879e-04, 9.9959737e-01],
       [9.9285066e-01, 7.1493387e-03],
       [9.9804151e-01, 1.9584293e-03],
       [1.8257918e-03, 9.

In [12]:
model.predict(new_data_inputs_scaled)[:,1].round(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([0.01, 0.  , 0.07, 1.  , 0.  , 0.06, 0.05, 0.13, 0.05, 0.8 , 0.  ,
       0.82, 0.94, 0.  , 0.12, 0.12, 0.87, 0.76, 0.86, 0.97, 1.  , 1.  ,
       1.  , 0.01, 0.  , 1.  , 0.54, 0.  , 1.  , 1.  ], dtype=float32)

In [13]:
np.argmax(model.predict(new_data_inputs_scaled),1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1])